### ISSUE TITLE
Compilation error: "Module not found: Can't resolve 'tsparticles'" after updating from 1.27.0 to latest 1.30.4

### ISSUE THREAD

**Issue by ShivamS136** [tsparticles/tsparticles#1769]
**Which version are you using?**
1.30.4

**Is the latest version affected?**

- [X] Yes
- [ ] No

**Which library are you using?**

- [ ] Vanilla JS (`tsparticles`)
- [X] React (`react-tsparticles`)
- [ ] Vue.js 2.x (`particles.vue`)
- [ ] Vue.js 3.x (`particles.vue3`)
- [ ] Angular (`ng-particles`)
- [ ] Svelte (`svelte-particles`)
- [ ] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

<details>
 <summary><b>tsParticles Configuration</b></summary>
  
  ```json
  {
	"particles": {
		"number": {
			"value": 80,
			"density": {
				"enable": true,
				"value_area": 500
			}
		},
		"color": {
			"value": "#eebbc3"
		},
		"shape": {
			"type": "circle",
			"stroke": {
				"width": 0,
				"color": "#eebbc3"
			},
			"polygon": {
				"nb_sides": 5
			},
			"image": {
				"src": "img/github.svg",
				"width": 100,
				"height": 100
			}
		},
		"opacity": {
			"value": 0.5,
			"random": true,
			"anim": {
				"enable": false,
				"speed": 1,
				"opacity_min": 0.1,
				"sync": false
			}
		},
		"size": {
			"value": 3,
			"random": true,
			"anim": {
				"enable": false,
				"speed": 40,
				"size_min": 0.1,
				"sync": false
			}
		},
		"line_linked": {
			"enable": true,
			"distance": 150,
			"color": "#b8c1ec",
			"opacity": 0.5,
			"width": 1
		},
		"move": {
			"enable": true,
			"speed": 2,
			"direction": "none",
			"random": false,
			"straight": false,
			"out_mode": "out",
			"bounce": false,
			"attract": {
				"enable": false,
				"rotateX": 600,
				"rotateY": 1200
			}
		}
	},
	"interactivity": {
		"detect_on": "canvas",
		"events": {
			"onhover": {
				"enable": true,
				"mode": "repulse"
			},
			"onclick": {
				"enable": true,
				"mode": "push"
			},
			"resize": true
		},
		"modes": {
			"grab": {
				"distance": 400,
				"line_linked": {
					"opacity": 1
				}
			},
			"bubble": {
				"distance": 400,
				"size": 40,
				"duration": 2,
				"opacity": 8,
				"speed": 3
			},
			"repulse": {
				"distance": 200,
				"duration": 0.4
			},
			"push": {
				"particles_nb": 4
			},
			"remove": {
				"particles_nb": 2
			}
		}
	},
	"retina_detect": true
}
  ```
</details>

**Describe the bug**
I was using `1.27.0` and everything was working fine, I updated using `npm update` and now my version is `1.30.4` and I am seeing below error on `npm run start`. PS. this app is created using `create-react-app` with default config.

```sh
D:\React\We-Were-Here>npm run start

> we-were-here@0.1.0 start D:\React\We-Were-Here
> react-scripts start

i ｢wds｣: Project is running at http://172.21.160.1/
i ｢wds｣: webpack output is served from /We-Were-Here
i ｢wds｣: Content not from webpack is served from D:\React\We-Were-Here\public
i ｢wds｣: 404s will fallback to /We-Were-Here/
Starting the development server...
Failed to compile.

./node_modules/react-tsparticles/cjs/particles.js
Module not found: Can't resolve 'tsparticles' in 'D:\React\We-Were-Here\node_modules\react-tsparticles\cjs'
Compiling...
Failed to compile.

./node_modules/react-tsparticles/cjs/particles.js
Module not found: Can't resolve 'tsparticles' in 'D:\React\We-Were-Here\node_modules\react-tsparticles\cjs'
```

**To Reproduce**
1. Clone [this repo](https://github.com/ShivamS136/We-Were-Here).
2. Run `npm install`.
3. Run `npm run start`
4. Everything is working fine as `react-tsparticles` version is `1.27.0`.
5. Now run `npm update`, `react-tsparticles` gets updated to version is `1.30.4`.
6. Run `npm run start`.
7. Observe the error in console.

**Expected behavior**
Compilation should be successful and the webpage should be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/32218762/124547061-30583c80-de49-11eb-9fb3-8de5fb11de7f.png)

**Desktop:**
 - OS: Windows 10
 - Browser: MS Edge
 - Version: 91.0.864.64

**Smartphone (please complete the following information):**
 Not tried

**Comment by matteobruni** [comment]
Hi @ShivamS136,

you can try Installing the `tsparticles` package, it should fix the error

**Comment by ShivamS136** [comment]
Hi @matteobruni,

Thanks, It's working fine now. 

Is it a breaking change from `1.27.0` to `1.30.4`? As previously it was working fine without separately installing `tsparticles`? It's not mentioned in [the doc](https://www.npmjs.com/package/react-tsparticles) as well.

**Comment by matteobruni** [comment]
Yes, I changed some dependencies to be peer dependencies and I forgot to update the README file

**Comment by ShivamS136** [comment]
Sorry for bothering you, but I am very new to Node, NPM, and react. So will it stay the same from now on i.e. install `tsparticles` separately OR in the future, you will make it the same as the previous one? As I think separate install may create confusion as having a package in `package.json` but not imported anywhere but required. But you are the expert, you know better.

**Comment by matteobruni** [comment]
The actual version is not gonna change, I prefer the peerDependency since the components will be more Indipendent, it’s a minor change since the main library is installed anyway, in one case automatically and in the other manually. The `”tsparticles”` import could happen sometimes since it has some additional exports that could help sometimes so it’s already there

**Comment by ShivamS136** [comment]
OK, Thanks @matteobruni, I'm closing it here. I hope `npm i tsparticles` was the right command to fix my issue which I performed. :)
