### PR TITLE
tsParticles 1.35.0

### LINKED ISSUE #2231: [Bug]: Custom typings of built-in libs are in conflict with the libs from TypeScript 4.4
### Contact Details

j.vanoostveen@afas.nl

### What happened?

When installing tsparticles in combination with TS4.4+, the lib.dom.d.ts reports an error because of a collision with typings of `Document` within this library.

```
node_modules/typescript/lib/lib.dom.d.ts:4256:11 - error TS2430: Interface 'Document' incorrectly extends interface 'FontFaceSource'.
  Types of property 'fonts' are incompatible.
    Type 'FontFaceSet' is missing the following properties from type 'FontFaceSet': onloading, onloadingdone, onloadingerror, forEach, and 13 more.

4256 interface Document extends Node, DocumentAndElementEventHandlers, DocumentOrShadowRoot, FontFaceSource, GlobalEventHandlers, NonElementParentNode, ParentNode, XPathEvaluatorBase {
```

I don't understand why there are global definition of the DOM in this library, but it would be preferred they are at least compatible with the built-in definitions provided by TypeScript self.

A minimal repro case can be found here: https://github.com/jvanoostveen/tsparticles-ts4.4

### Version

1.19.1

### Which library are you using?

Vanilla (tsparticles)

### tsParticles Configuration

```json
(any configuration will do...)

confetti(`confettiWrapper`, {
  angle: 90,
  count: 5,
  position: { x: 100, y: 100 },
  spread: 100,
  startVelocity: 75,
  decay: 0.8,
  gravity: 2,
  drift: 0,
  ticks: 75,
  colors: ['#ff0000', '#ff8400', '#ffea00', '#00ff00', '#00bbff', '#0000ff', '#ff00ff'],
  shapes: ['circle'],
  scalar: 1.25,
  zIndex: 2000,
  disableForReducedMotion: true
});
```

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell
node_modules/typescript/lib/lib.dom.d.ts:4256:11 - error TS2430: Interface 'Document' incorrectly extends interface 'FontFaceSource'.
  Types of property 'fonts' are incompatible.
    Type 'FontFaceSet' is missing the following properties from type 'FontFaceSet': onloading, onloadingdone, onloadingerror, forEach, and 13 more.

4256 interface Document extends Node, DocumentAndElementEventHandlers, DocumentOrShadowRoot, FontFaceSource, GlobalEventHandlers, NonElementParentNode, ParentNode, XPathEvaluatorBase {
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by matteobruni**
# tsParticles 1.35.0

## Internal updates
- Split some polygon-mask files, nothing affecting output
- Updated code to work with TypeScript 4.4 (except angular and svelte for now)
- Moved some code out from particle constructor to updaters

## New Features

- Added roll mode to use only horizontal, vertical or both rolling
- Added auto options to theme default to change theme automatically
- Created a custom pathseg for now with some removed types in TypeScript 4.4, sent PR to the original project https://github.com/progers/pathseg/pull/32 to add them in the polyfill. It's nomore required when using PolygonMask since is dynamically imported if needed

### CODE REVIEW

**Comment by ghost** [comment]
## DeepCode's analysis on [#1b4ba0](https://www.deepcode.ai/app/gh/matteobruni/tsparticles/da1b5a9db72f56eb4930990cc0f7967ff28bb781/matteobruni/tsparticles/1b4ba0f2a7bf37e88e5fd92ac0709c31c1b40ae7/pr/_/%2F/code/?utm_source=gh_review&c=0&w=3&i=4&) found:

- :warning: **3** warnings, :information_source: **4** minor issues. :point_down:
## Top issues

<table>
  <thead>
    <tr>
      <th align="left">Description</th>
      <th align="left">Example fixes</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td width="77%">Using isNaN may lead to unexpected results. Consider the more robust Number.isNaN instead. Occurrences: <ul><li><a href="https://github.com/matteobruni/tsparticles/blob/1b4ba0f2a7bf37e88e5fd92ac0709c31c1b40ae7/utils/pathseg/pathseg.js#L471">pathseg.js:471</a></li></ul></td>
      <td width="23%"><a href="https://www.deepcode.ai/app/gh/matteobruni/tsparticles/da1b5a9db72f56eb4930990cc0f7967ff28bb781/matteobruni/tsparticles/1b4ba0f2a7bf37e88e5fd92ac0709c31c1b40ae7/pr/_/%2Futils%2Fpathseg%2Fpathseg.js/javascript%2Fdc_interfile_project%2FUseNumberIsNan/code/?utm_source=gh_review&">:wrench: Example fixes</a></td>
    </tr>
    <tr>
      <td width="77%">Testing a collection size for < 0 will always be false. Occurrences: <ul><li><a href="https://github.com/matteobruni/tsparticles/blob/1b4ba0f2a7bf37e88e5fd92ac0709c31c1b40ae7/engine/src/Plugins/Absorbers/AbsorberInstance.ts#L98">AbsorberInstance.ts:98</a></li></ul></td>
      <td width="23%"><a href="https://www.deepcode.ai/app/gh/matteobruni/tsparticles/da1b5a9db72f56eb4930990cc0f7967ff28bb781/matteobruni/tsparticles/1b4ba0f2a7bf37e88e5fd92ac0709c31c1b40ae7/pr/_/%2Fengine%2Fsrc%2FPlugins%2FAbsorbers%2FAbsorberInstance.ts/javascript%2Fdc_interfile_project%2FCollectionArraySizeMatch/code/?utm_source=gh_review&">:wrench: Example fixes</a></td>
    </tr>
    <tr>
      <td width="77%">Two subsequent branches of an if statement have duplicate bodies (here and here). This may be caused by a copy-paste error. If this usage is intentional, consider merging the branches to avoid code duplication. Occurrences: <ul><li><a href="https://github.com/matteobruni/tsparticles/blob/1b4ba0f2a7bf37e88e5fd92ac0709c31c1b40ae7/engine/src/Plugins/Absorbers/plugin.ts#L44">plugin.ts:44</a></li></ul></td>
      <td width="23%"><a href="https://www.deepcode.ai/app/gh/matteobruni/tsparticles/da1b5a9db72f56eb4930990cc0f7967ff28bb781/matteobruni/tsparticles/1b4ba0f2a7bf37e88e5fd92ac0709c31c1b40ae7/pr/_/%2Fengine%2Fsrc%2FPlugins%2FAbsorbers%2Fplugin.ts/javascript%2Fdc_interfile_project%2FDuplicateIfBody/code/?utm_source=gh_review&">:wrench: Example fixes</a></td>
    </tr>
  </tbody>
</table>


#### 👉 View analysis in [**DeepCode’s Dashboard**](https://www.deepcode.ai/app/gh/matteobruni/tsparticles/da1b5a9db72f56eb4930990cc0f7967ff28bb781/matteobruni/tsparticles/1b4ba0f2a7bf37e88e5fd92ac0709c31c1b40ae7/pr/_/%2F/code/?utm_source=gh_review&c=0&w=3&i=4&) | [_Configure the bot_](https://www.deepcode.ai/app/gh/?ownerconfig=matteobruni)
#### 👉 The DeepCode service and API will be deprecated in August, 2021. [Here](https://www.deepcode.ai/blog/migrate-to-snyk-code) is the information how to migrate. Thank you for using DeepCode 🙏 ❤️ !
If you are using our plugins, you might be interested in their successors: [Snyk's JetBrains plugin](https://snyk.co/udpkq) and [Snyk's VS Code plugin](https://snyk.co/udpkr).
