### ISSUE TITLE
ng-particles: Cannot find module 'tsparticles' or its corresponding type declarations.

### ISSUE THREAD

**Issue by j0nm1** [tsparticles/tsparticles#1683]
**Which version are you using?**
```
ng-particles: 2.12.2
tsparticles: 1.29.2
```

**Is the latest version affected?**
- [x] Yes
- [ ] No

**Which library are you using?**

- [x] Vanilla JS (`tsparticles`)
- [x] Angular (`ng-particles`)

**Describe the bug**

The problem exists when compiling an Angular application that uses `ng-particles` and `tsparticles` without `"skipLibCheck": true` in the `tsconfig.json`.

The error is:
```
Error: node_modules/ng-particles/lib/ng-particles.component.d.ts:2:38 - error TS2307: Cannot find module 'tsparticles' or its corresponding type declarations.

2 import type { Container, Main } from 'tsparticles';
                                       ~~~~~~~~~~~~~


Error: node_modules/ng-particles/lib/ng-particles.module.d.ts:1:37 - error TS2307: Cannot find module 'tsparticles' or its corresponding type declarations.

1 import type { ISourceOptions } from 'tsparticles';
                                      ~~~~~~~~~~~~~


Error: node_modules/ng-particles/lib/ng-particles.module.d.ts:9:15 - error TS2307: Cannot find module 'tsparticles' or its corresponding type declarations.

9 export * from 'tsparticles';
                ~~~~~~~~~~~~~
```

With `ng-particles: 2.12.2` and  `tsparticles: 1.27.0` the problem does not exist, but I would like to update my application to the newest version. Furthermore setting `"skipLibCheck": true` in the `tsconfig.json` does solve it as well (but I don't think this is a good solution). Maybe it's related to https://github.com/matteobruni/tsparticles/issues/1472?

**Comment by matteobruni** [comment]
Hi @j0nm1,

The other issue was fixed, it was an error in the react component type definition.

What is your TypeScript version? I had some issues with TypeScript <=4.0 and I’m working on a fix that will be out soon (I don’t know how soon yet)

**Comment by j0nm1** [comment]
Hi, thanks for the quick reply. I'm using `typescript: 4.0.8`

**Comment by matteobruni** [comment]
Ok that’s the issue, there are broken types definitions for TypeScript <4.1, you can try with `1.29.0`, this version should work, the `1.29.2` has some changes that didn’t work as expected

**Comment by j0nm1** [comment]
Downgrading to version `1.29.0` did not work. But after updating `typescript` to `4.1.6` it works with `1.29.2`.
For me, the problem is resolved with this solution. Thank you!

**Comment by matteobruni** [comment]
Thank you @j0nm1 for the test, I’ll investigate more about that before releasing an update
