### ISSUE TITLE
[Bug]: Not working cause of => interactor.init is not a function

### ISSUE THREAD

**Issue by Ackermiam** [tsparticles/tsparticles#5391]
### Contact Details

On github 

### What happened?

Not working on Vue 3.4.37, and tsparticles 2.12.0, here's my dependencies :

```json
"dependencies": {
    "tsparticles": "^3.5.0",
    "tsparticles-engine": "^2.12.0",
    "vue": "^3.4.37",
    "vue3-particles": "^2.12.0"
  },
```
Here's my component :

```vue
<template>
  <div class="Narrative">
    <Particles
      id="tsparticles"
      :particlesInit="particlesInit"
      :particlesLoaded="particlesLoaded"
      :options="particlesoptions"
    />
  </div>
</template>

<script setup lang="ts">
import type { Engine } from 'tsparticles-engine';
import { loadFull } from "tsparticles";

const particlesInit = async (engine: Engine) => {
  await loadFull(engine);
};

const particlesLoaded = async (container) => {
  console.log("Particles container loaded", container);
};

const particlesoptions = {
  particles: {
    number: {
      value: 100,
    },
    move: {
      direction: "bottom",
      enable: true,
      random: false,
      straight: false,
    },
    color: {
      value: "#F599FF",
    },
    opacity: {
      value: { min: 0.1, max: 0.5 },
    },
    size: {
      value: { min: 1, max: 10 },
    },
    wobble: {
      distance: 20,
      enable: true,
      speed: {
        min: -5,
        max: 5,
      },
    },
  },
};
</script>
```

And my main.ts :

```ts
import { createApp } from 'vue'
import './style.css'
import App from './App.vue'
import Particles from "vue3-particles"

createApp(App).use(Particles).mount("#app");
```

And the error 

```
vue3-particles.js?v=ecce0f0f:3068 Uncaught (in promise) TypeError: interactor.init is not a function
    at InteractionManager.init (vue3-particles.js?v=ecce0f0f:3068:18)
    at Particles.init (vue3-particles.js?v=ecce0f0f:3645:30)
    at Container.init (vue3-particles.js?v=ecce0f0f:4091:20)
    at async Container.start (vue3-particles.js?v=ecce0f0f:4193:5)
    at async Engine._loadParams (vue3-particles.js?v=ecce0f0f:4649:5)
    at async vue3-particles.js?v=ecce0f0f:4767:92
```

How fix this issue ? Thanks you a lot !

### tsParticles Version

2.12.0

### tsParticles Configuration

```json
{
  particles: {
    number: {
      value: 100,
    },
    move: {
      direction: "bottom",
      enable: true,
      random: false,
      straight: false,
    },
    color: {
      value: "#F599FF",
    },
    opacity: {
      value: { min: 0.1, max: 0.5 },
    },
    size: {
      value: { min: 1, max: 10 },
    },
    wobble: {
      distance: 20,
      enable: true,
      speed: {
        min: -5,
        max: 5,
      },
    },
  },
}
```

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
vue3-particles.js?v=ecce0f0f:3068 Uncaught (in promise) TypeError: interactor.init is not a function
    at InteractionManager.init (vue3-particles.js?v=ecce0f0f:3068:18)
    at Particles.init (vue3-particles.js?v=ecce0f0f:3645:30)
    at Container.init (vue3-particles.js?v=ecce0f0f:4091:20)
    at async Container.start (vue3-particles.js?v=ecce0f0f:4193:5)
    at async Engine._loadParams (vue3-particles.js?v=ecce0f0f:4649:5)
    at async vue3-particles.js?v=ecce0f0f:4767:92
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ackermiam** [comment]
EDIT:

If I cut the ':particlesInit="particlesInit"' in my Vue component :

```vue
    <Particles
      id="tsparticles"
      :particlesInit="particlesInit"
      :particlesLoaded="particlesLoaded"
      :options="particlesoptions"
    />
```

There's no error in console, the "particlesLoaded" function print the data in console, the canvas appears correctly in DOM, but the particles doesn't appears

**Comment by Ackermiam** [comment]
Ok guys, finally found a solution !

/!\ Don't follow theses instructions if you want to use this library with vue 3.4 => https://www.youtube.com/watch?v=-QREr35VFBQ and https://github.com/tsparticles/vue3-demo /!\

I don't know why but, in the documentation there's no mentions to ALL packages you need to install, here's the complete packages to install :

```json
  "dependencies": {
    "@tsparticles/engine": "^3.5.0",
    "@tsparticles/slim": "^3.5.0",
    "@tsparticles/vue3": "^3.0.1"
  },
```

Make a main.ts like this :

```ts
import { createApp } from 'vue'
import './style.css'
import App from './App.vue'
import Particles from '@tsparticles/vue3';
import { loadSlim } from "@tsparticles/slim";

createApp(App).use(Particles, {
  init: async engine => {
    await loadSlim(engine);
  }
}).mount("#app");
```

And as the way that's presented here in template (https://github.com/tsparticles/vue3) :

Put your component and its options :

```vue
<template>
  <div class="Narrative">
    <vue-particles id="tsparticles" @particles-loaded="particlesLoaded" :options="particlesoptions" />
  </div>
</template>

<script setup lang="ts">
const particlesLoaded = async (container) => {
  console.log("Particles container loaded", container);
};

const particlesoptions = {
  particles: {
    number: {
      value: 100,
    },
    move: {
      direction: "bottom",
      enable: true,
      random: false,
      straight: false,
    },
    color: {
      value: "#F599FF",
    },
    opacity: {
      value: { min: 0.1, max: 0.5 },
    },
    size: {
      value: { min: 1, max: 10 },
    },
    wobble: {
      distance: 20,
      enable: true,
      speed: {
        min: -5,
        max: 5,
      },
    },
  },
};
</script>
```

And it should work !

It's possible to update the documentation to post the full dependencies to install for project in Vue 3.4 ? Thanks you very much ! :D

**Comment by matteobruni** [comment]
If you have problems in Vue 3.x, please open an issue in the Vue 3 repository: https://github.com/tsparticles/vue3
